name: Updater

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update
        run: python update_data.py

      - name: Commit
        run: |
          git config --global user.name " gbf-spark-image "
          git config --global user.email " gbf-spark-image @users.noreply.github.com"
          git add .
          git commit -m "Update"
          git push

      - name: Build
        run: |
          npm install
          npm run generate
          "" > .output/public/.nojekyll
          git add .output/public -f
          git commit -m "Update"
          git subtree split --prefix .output/public -b gh-pages
          git push -f origin gh-pages:gh-pages
